version: '3'

services:

  db:
    container_name: mysql
    image: mysql:8
    platform: linux/amd64
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: starter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
    name: skynet
